# Granger Causality

## Introduction to Granger Causality Test

Granger Causality Test is used to find out if one series can forecast another series. The null hypothesis for Granger Causality Tests is that the time series in the second column, x2, does NOT Granger cause the time series in the first column, x1. Granger causality means that past values of x2 have a statistically significant effect on the current value of x1, taking past values of x1 into account as regressors. We reject the null hypothesis that x2 does not Granger cause x1 if the p-values are below a desired size of the test. If the p-values are less than a significant threshold level, usually 0.05, then you reject the null hypothesis and conclude that the lag of X is useful.

Source:  https://www.statsmodels.org/devel/generated/statsmodels.tsa.stattools.grangercausalitytests.html

In [1]:
import pandas as pd
import numpy as np

## Example 1: Vacation Dataset

In [2]:
# This is the stationarized dataset

vacation = pd.read_csv("vacation_firstdiff.csv", parse_dates=['Month'])
vacation.head()

Month  first_diff
0 2004-04-01        -7.0
1 2004-05-01        10.0
2 2004-06-01         9.0
3 2004-07-01        -2.0
4 2004-08-01       -17.0

In [3]:
vacation['month_only'] = pd.DatetimeIndex(vacation['Month']).month

In [4]:
vacation.head()

Month  first_diff  month_only
0 2004-04-01        -7.0           4
1 2004-05-01        10.0           5
2 2004-06-01         9.0           6
3 2004-07-01        -2.0           7
4 2004-08-01       -17.0           8

In [5]:
new_df = vacation[['first_diff', 'month_only']]
new_df.head()

first_diff  month_only
0        -7.0           4
1        10.0           5
2         9.0           6
3        -2.0           7
4       -17.0           8

In [6]:
#The Null hypothesis is: the series in the second column, does not Granger cause the series in the first.
# The second argument maxlag specifies how many lags of Y should be included in the test.
import statsmodels.api as sm
from statsmodels.tsa.stattools import grangercausalitytests

grangercausalitytests(new_df[['first_diff', 'month_only']], maxlag=12)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=25.0900 , p=0.0000  , df_denom=183, df_num=1
ssr based chi2 test:   chi2=25.5013 , p=0.0000  , df=1
likelihood ratio test: chi2=23.8981 , p=0.0000  , df=1
parameter F test:         F=25.0900 , p=0.0000  , df_denom=183, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=10.6917 , p=0.0000  , df_denom=180, df_num=2
ssr based chi2 test:   chi2=21.9773 , p=0.0000  , df=2
likelihood ratio test: chi2=20.7668 , p=0.0000  , df=2
parameter F test:         F=10.6917 , p=0.0000  , df_denom=180, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=9.7996  , p=0.0000  , df_denom=177, df_num=3
ssr based chi2 test:   chi2=30.5615 , p=0.0000  , df=3
likelihood ratio test: chi2=28.2736 , p=0.0000  , df=3
parameter F test:         F=9.7996  , p=0.0000  , df_denom=177, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=6.6611  , p=0.0001  

{1: ({'ssr_ftest': (25.089990168802437, 1.2825651273652184e-06, 183.0, 1),
   'ssr_chi2test': (25.5013014830451, 4.420846013563039e-07, 1),
   'lrtest': (23.89811297093047, 1.0157127543966596e-06, 1),
   'params_ftest': (25.0899901688024, 1.2825651273652493e-06, 183.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (10.69165170928395, 4.0965098774766366e-05, 180.0, 2),
   'ssr_chi2test': (21.977284069083673, 1.689247950904243e-05, 2),
   'lrtest': (20.766846323191885, 3.094116185666677e-05, 2),
   'params_ftest': (10.691651709283931, 4.096509877476682e-05, 180.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (9.799616131907152, 5.158807108299026e-06, 177.0, 3),
   'ssr_chi2test': (30.561514716456205, 1.0513557113478065e-06, 3),
   'lrtest': (28.273572763345328, 3.182144140198665e-06, 3),
   'params_ftest': (9.799616131907165, 5.158807108298964e-06, 177.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1.,

We can reject the null hypothesis that months does not Granger cause vacation.  The p-values are all zeros, which suggests statistical significance under 0.05 threshold.  We can infer that months does have an effect on vacation, which is in alignment with our expectation. 

## Example 2: Spotify and Netflix Dataset

In [7]:
df = pd.read_csv('SpotifyNetflix.csv', index_col = 0, parse_dates=True)
df.head()

NFLX        SPOT
Date                              
2018-07-02  398.179993  170.690002
2018-07-03  390.519989  168.660004
2018-07-05  398.390015  176.440002
2018-07-06  408.250000  175.699997
2018-07-09  418.970001  177.440002

In [8]:
df = df.resample('W').last()
df = df.pct_change()  # calculate the return
df = df.dropna()
df.head()

NFLX      SPOT
Date                          
2018-07-15 -0.030496  0.065509
2018-07-22 -0.087797 -0.023610
2018-07-29 -0.016175  0.019038
2018-08-05 -0.034121 -0.057819
2018-08-12  0.008103  0.077265

In [9]:
df2 = df[['NFLX', 'SPOT']]
df2.head()

NFLX      SPOT
Date                          
2018-07-15 -0.030496  0.065509
2018-07-22 -0.087797 -0.023610
2018-07-29 -0.016175  0.019038
2018-08-05 -0.034121 -0.057819
2018-08-12  0.008103  0.077265

In [10]:
#The Null hypothesis is: the series in the second column, does not Granger cause the series in the first.
# The second argument maxlag specifies how many lags of Y should be included in the test.
import statsmodels.api as sm
from statsmodels.tsa.stattools import grangercausalitytests

grangercausalitytests(df2[['NFLX', 'SPOT']], maxlag=21)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0045  , p=0.9466  , df_denom=62, df_num=1
ssr based chi2 test:   chi2=0.0047  , p=0.9451  , df=1
likelihood ratio test: chi2=0.0047  , p=0.9451  , df=1
parameter F test:         F=0.0045  , p=0.9466  , df_denom=62, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0469  , p=0.9543  , df_denom=59, df_num=2
ssr based chi2 test:   chi2=0.1016  , p=0.9504  , df=2
likelihood ratio test: chi2=0.1016  , p=0.9505  , df=2
parameter F test:         F=0.0469  , p=0.9543  , df_denom=59, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.3432  , p=0.7942  , df_denom=56, df_num=3
ssr based chi2 test:   chi2=1.1583  , p=0.7630  , df=3
likelihood ratio test: chi2=1.1478  , p=0.7655  , df=3
parameter F test:         F=0.3432  , p=0.7942  , df_denom=56, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2299  , p=0.9204  , df_d

{1: ({'ssr_ftest': (0.004523072212910248, 0.9465960785399432, 62.0, 1),
   'ssr_chi2test': (0.004741930545793001, 0.9450997234765773, 1),
   'lrtest': (0.004741757585691175, 0.9451007231374311, 1),
   'params_ftest': (0.004523072212911903, 0.9465960785399432, 62.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.04685268083232807, 0.9542634297419279, 59.0, 2),
   'ssr_chi2test': (0.10164649400911852, 0.9504466499789448, 2),
   'lrtest': (0.10156586054779382, 0.9504849696529978, 2),
   'params_ftest': (0.046852680832331774, 0.9542634297419248, 59.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.34320947170506516, 0.7941612663469351, 56.0, 3),
   'ssr_chi2test': (1.1583319670045948, 0.763014373916665, 3),
   'lrtest': (1.147812044921011, 0.7655463736423974, 3),
   'params_ftest': (0.34320947170506827, 0.7941612663469335, 56.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0

We do not find statistical significance as the p-values are all high values. We maintain that the Spotify series does not Granger Cause Netflix series.

## Example 5: Bank of America and J.P. Morgan

In [11]:
# This is the data from section 2.3 when we detrend and deseasonalized
bac = pd.read_csv("bac_return.csv", index_col=0, parse_dates=True)
bac.head()

return
Date                
1990-01-14 -0.050000
1990-01-21  0.035088
1990-01-28 -0.028249
1990-02-04 -0.002907
1990-02-11 -0.017493

In [12]:
# This is the data from section 2.3 when we detrend and deseasonalized
jpm = pd.read_csv("jpm_return.csv", index_col=0, parse_dates=True)
jpm.head()

return
Date                
1990-01-14 -0.056000
1990-01-21 -0.021186
1990-01-28 -0.082251
1990-02-04 -0.014151
1990-02-11 -0.009570

In [13]:
frames = [bac, jpm]
new_df = pd.concat(frames, axis = 1)
column_names = ['bac', 'jpm']
new_df.columns = column_names
new_df.head()

bac       jpm
Date                          
1990-01-14 -0.050000 -0.056000
1990-01-21  0.035088 -0.021186
1990-01-28 -0.028249 -0.082251
1990-02-04 -0.002907 -0.014151
1990-02-11 -0.017493 -0.009570

In [14]:
#The Null hypothesis is: the series in the second column, does not Granger cause the series in the first.
# The second argument maxlag specifies how many lags of Y should be included in the test.
import statsmodels.api as sm
from statsmodels.tsa.stattools import grangercausalitytests

grangercausalitytests(new_df[['bac', 'jpm']], maxlag=24)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=5.3276  , p=0.0211  , df_denom=1550, df_num=1
ssr based chi2 test:   chi2=5.3379  , p=0.0209  , df=1
likelihood ratio test: chi2=5.3287  , p=0.0210  , df=1
parameter F test:         F=5.3276  , p=0.0211  , df_denom=1550, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=3.9817  , p=0.0188  , df_denom=1547, df_num=2
ssr based chi2 test:   chi2=7.9891  , p=0.0184  , df=2
likelihood ratio test: chi2=7.9686  , p=0.0186  , df=2
parameter F test:         F=3.9817  , p=0.0188  , df_denom=1547, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.6031  , p=0.0505  , df_denom=1544, df_num=3
ssr based chi2 test:   chi2=7.8446  , p=0.0493  , df=3
likelihood ratio test: chi2=7.8248  , p=0.0498  , df=3
parameter F test:         F=2.6031  , p=0.0505  , df_denom=1544, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=3.9711  , p=0.

{1: ({'ssr_ftest': (5.327570602009757, 0.02112172269358556, 1550.0, 1),
   'ssr_chi2test': (5.337882028981389, 0.02086681071718848, 1),
   'lrtest': (5.328729465307333, 0.02097667145639206, 1),
   'params_ftest': (5.327570602009863, 0.02112172269358436, 1550.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (3.9816839442995007, 0.018845692979947832, 1547.0, 2),
   'ssr_chi2test': (7.989105987786457, 0.018415676490983898, 2),
   'lrtest': (7.968613841321712, 0.01860533482831761, 2),
   'params_ftest': (3.9816839442995278, 0.0188456929799443, 1547.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (2.603067728331706, 0.05051089490028585, 1544.0, 3),
   'ssr_chi2test': (7.8446076035799415, 0.049334772550768534, 3),
   'lrtest': (7.8248361155201565, 0.04977398462130874, 3),
   'params_ftest': (2.6030677283315726, 0.05051089490029332, 1544.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          

Does the J.P. Morgan time series data help us to forecast the Bank of America time series data? Yes. There is strong statistical significance. The p-values are below the 0.05 threshold so we can reject the null hypothesis. We can claim that J.P. Morgan's time series data does "granger cause" Bank of America's time series data for the 24 months of lagged data that we observed. 

In [ ]:
# end